# Server Port Settings
server:
  port: 9091

spring:
  profiles: dev

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/toy
    username: testuser
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

stubhub:
  access-url: https://api.stubhub.com/sellers/oauth/accesstoken
  event-url: https://api.stubhub.com/sellers/search/events/v3
  key:
  secret:
  username:
  password:
---
